// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Email     string
}
